services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-9(ry2rm_^qy_zt7+36!y#p$tqdiy9be7^54rd)!p+msxubm%05"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:16
    volumes:
      - books_postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  books_postgres_data:
